apiVersion: v1
kind: Service
metadata:
  name: {{ include "hola-mundo.fullname" . }}
  labels: 
    {{- include "hola-mundo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: 
    {{- include "hola-mundo.selectorLabels" . | nindent 4 }}
